### ISSUE TITLE
Defining Type in sizeof Expression Causes Arduino Build to Fail

### ISSUE THREAD

**Issue by bramwelt** [01org/tinycbor#16] opened 2015-09-30 18:04 UTC
The IoTivity Arduino build fails against the latest version of `tinycbor` (4e9626cd160d81e0f9bde4ecc3b73024db101e40)

#### avr-g++ version
```
$ extlibs/arduino/arduino-1.5.8/hardware/tools/avr/bin/avr-g++ --version
avr-g++ (GCC) 4.8.1
```
#### avr-g++ compilation command
```
avr-g++ -o extlibs/tinycbor/tinycbor/src/cborencoder.o -c -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -Wall -Os -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=158 -DARDUINO_AVR_MEGA2560 -std=c99 -DARDUINO_ARCH_AVR -DNDEBUG -DWITH_ARDUINO -D__ARDUINO__ -D__OIC_DEVICE_NAME__='"OIC-DEVICE"' -DNO_EDR_ADAPTER -DNO_LE_ADAPTER -DIP_ADAPTER -DNO_TCP_ADAPTER -DROUTING_EP -DSINGLE_THREAD -Iout/arduino/avr/release/extlibs/cjson -Iextlibs/cjson -Iout/arduino/avr/release/extlibs/timer -Iextlibs/timer -Iout/arduino/avr/release/resource/csdk/logger/include -Iresource/csdk/logger/include -Iout/arduino/avr/release/resource/csdk/ocrandom/include -Iresource/csdk/ocrandom/include -Iout/arduino/avr/release/resource/csdk/stack/include -Iresource/csdk/stack/include -Iout/arduino/avr/release/resource/csdk/stack/include/internal -Iresource/csdk/stack/include/internal -Iout/arduino/avr/release/resource/oc_logger/include -Iresource/oc_logger/include -Iout/arduino/avr/release/resource/csdk/connectivity/lib/libcoap-4.1.1 -Iresource/csdk/connectivity/lib/libcoap-4.1.1 -Iout/arduino/avr/release/resource/csdk/connectivity/inc -Iresource/csdk/connectivity/inc -Iout/arduino/avr/release/resource/csdk/connectivity/api -Iresource/csdk/connectivity/api -Iout/arduino/avr/release/resource/csdk/connectivity/external/inc -Iresource/csdk/connectivity/external/inc -Iout/arduino/avr/release/resource/csdk/security/include -Iresource/csdk/security/include -Iout/arduino/avr/release/resource/csdk/security/include/internal -Iresource/csdk/security/include/internal -Iout/arduino/avr/release/resource/api -Iresource/api -Ideps/arduino/include -Iextlibs/tinycbor/tinycbor/src -Iextlibs/arduino/arduino-1.5.8/hardware/arduino/avr/variants/mega -Iextlibs/arduino/arduino-1.5.8/hardware/arduino/avr/cores/arduino -Iextlibs/arduino/arduino-1.5.8/hardware/arduino/avr/libraries/SPI -Iextlibs/arduino/arduino-1.5.8/libraries/Ethernet/src -Iextlibs/arduino/arduino-1.5.8/libraries/Ethernet/src/utility -Iextlibs/arduino/arduino-1.5.8/libraries/Time/Time -Iout/arduino/avr/release/resource/c_common -Iresource/c_common -Iout/arduino/avr/release/resource/c_common/oic_malloc/include -Iresource/c_common/oic_malloc/include -Iout/arduino/avr/release/resource/c_common/oic_string/include -Iresource/c_common/oic_string/include -Iout/arduino/avr/release/resource/inc -Iresource/inc -Iout/arduino/avr/release/resource/lib/libcoap-4.1.1 -Iresource/lib/libcoap-4.1.1 -Iout/arduino/avr/release/resource/common/inc -Iresource/common/inc -Iout/arduino/avr/release/resource/csdk/common/inc -Iresource/csdk/common/inc -Iout/arduino/avr/release/resource/csdk/ip_adapter/arduino -Iresource/csdk/ip_adapter/arduino -Iout/arduino/avr/release/resource/csdk/routing/include -Iresource/csdk/routing/include extlibs/tinycbor/tinycbor/src/cborencoder.c
```
#### Error Output
```
In file included from extlibs/tinycbor/tinycbor/src/cborencoder.c:28:0:
extlibs/tinycbor/tinycbor/src/cborencoder.c: In function 'CborError create_container(CborEncoder*, CborEncoder*, size_t, uint8_t)':
extlibs/tinycbor/tinycbor/src/compilersupport_p.h:41:62: error: types may not be defined in 'sizeof' expressions
 #  define cbor_static_assert(x)         ((void)sizeof(struct { int m : 2*!!(x) - 1; }))
                                                              ^
extlibs/tinycbor/tinycbor/src/cborencoder.c:235:5: note: in expansion of macro 'cbor_static_assert'
     cbor_static_assert(((MapType << MajorTypeShift) & CborIteratorFlag_ContainerIsMap) == CborIteratorFlag_ContainerIsMap);
     ^
extlibs/tinycbor/tinycbor/src/compilersupport_p.h:41:62: error: types may not be defined in 'sizeof' expressions
 #  define cbor_static_assert(x)         ((void)sizeof(struct { int m : 2*!!(x) - 1; }))
                                                              ^
extlibs/tinycbor/tinycbor/src/cborencoder.c:236:5: note: in expansion of macro 'cbor_static_assert'
     cbor_static_assert(((ArrayType << MajorTypeShift) & CborIteratorFlag_ContainerIsMap) == 0);
     ^
scons: *** [extlibs/tinycbor/tinycbor/src/cborencoder.o] Error 1
```

Please let me know if you need more information for confirming or diagnosing this!

**Comment by thiagomacieira** [comment] 2015-09-30 19:04
Hi Trevor

I can confirm it. It's caused by the cbor_static_assert macro. The solution I used for non-C++11 and non-C11 appears not to work in C++98 mode. A simple solution, for now, is to pass -std=c++11 to your compiler.

I'll make a fix for this.

**Closed** 2015-09-30 19:56 UTC
